export const SUBSCRIPTION_PLANS = [
  {
    name: "Open Source",
    price: "Free",
    icon: "🆓",
    description: "Perfect for individual developers getting started",
    features: [
      "Free for all local usage",
      "Unlimited clients",
      "Basic configuration management",
      "Local storage",
      "Community support",
      "Access to open-source code",
    ],
    earlyAccess: false,
    popular: false,
    ctaText: "Get Started",
    ctaVariant: "outline" as const,
  },
  {
    name: "Professional",
    price: "$29",
    originalPrice: "$49",
    period: "/month",
    icon: "💼",
    description: "Enhanced features for professional developers",
    features: [
      "Everything in free plan",
      "Cloud encrypted backup",
      "Multi-device synchronization",
      "Configuration template library",
      "Automatic configuration validation",
      "Priority support",
      "Advanced analytics",
    ],
    earlyAccess: true,
    popular: true,
    ctaText: "Start 7-day Free Trial",
    ctaVariant: "default" as const,
  },
  {
    name: "Team",
    price: "$99",
    originalPrice: "$199",
    period: "/month",
    icon: "👥",
    description: "Collaboration tools for development teams",
    features: [
      "Everything in Pro plan",
      "Team configuration sharing",
      "Permission management",
      "Usage statistics & insights",
      "Team collaboration tools",
      "Admin dashboard",
      "24/7 priority support",
      "Custom integrations",
      "Advanced security features",
    ],
    earlyAccess: true,
    popular: false,
    ctaText: "Start 7-day Free Trial",
    ctaVariant: "default" as const,
  }
];
