export const SUBSCRIPTION_PLANS = [
  {
    name: "Open Source",
    price: "Free",
    icon: "🆓",
    description: "Perfect for individual developers getting started",
    features: [
      "5 client synchronizations (sufficient for most users)",
      "Basic configuration management",
      "Local storage",
      "Community support",
      "Open source code access",
    ],
    popular: false,
    ctaText: "Get Started",
    ctaVariant: "outline" as const,
  },
  {
    name: "Professional",
    price: "$29",
    period: "/month",
    icon: "💼",
    description: "Enhanced features for professional developers",
    features: [
      "Cloud encrypted backup",
      "Multi-device synchronization",
      "Configuration template library",
      "Automatic configuration validation",
      "Priority support",
      "Advanced analytics",
    ],
    popular: true,
    ctaText: "Start 7 days Free Trial",
    ctaVariant: "default" as const,
  },
  {
    name: "Team",
    price: "$99",
    period: "/month",
    icon: "👥",
    description: "Collaboration tools for development teams",
    features: [
      "Team configuration sharing",
      "Permission management",
      "Usage statistics & insights",
      "Team collaboration tools",
      "Admin dashboard",
      "24/7 priority support",
      "Custom integrations",
      "Advanced security features",
    ],
    popular: false,
    ctaText: "Contact Sales",
    ctaVariant: "outline" as const,
  },
];
